#################################
# Configuration for LobbyCore #
#################################

// use § for text color

# Item names (for the teleport items):

Game-1-Name: SkyBlock
Game-2-Name: SkyWars
Game-3-Name: BedWars
Game-4-Name: TNTRun


# Transfer (for the teleport / UI form):

ip-port: transferserver 149.202.215.215 41127

# BossBar EDIT

head-message: "BossBar"
changing-messages:
  - "{0%}§l§eSuscribe Minecraft PE Hindi For More!"
  - "{10%}§l§eplay games?"
  - "{50%}§l§cHave Fun On Server"
  - "{100%}§l§cLegends never surrendered"
change-speed: 8
worlds: []
